package com.luvsoft.entities;

// Generated Jan 26, 2016 10:06:12 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Material generated by hbm2java
 */
@Entity
@Table(name = "material", catalog = "stockmanagement")
public class Material extends AbstractEntity implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = -2197151457409452544L;
    private Integer id;
    private Materialtype1 materialtype1;
    private Materialtype2 materialtype2;
    private Stock stock;
    private Unit unit;
    private String code;
    private String name;
    private BigDecimal price;
    private int quantity;
    private String description;
    private Set<Coupondetail> coupondetails = new HashSet<Coupondetail>(0);
    private Set<Orderdetail> orderdetails = new HashSet<Orderdetail>(0);

    public Material() {
    }

    public Material(Materialtype1 materialtype1, Materialtype2 materialtype2, Stock stock, String code, String name, BigDecimal price, int quantity) {
        this.materialtype1 = materialtype1;
        this.materialtype2 = materialtype2;
        this.stock = stock;
        this.code = code;
        this.name = name;
        this.price = price;
        this.quantity = quantity;
    }

    public Material(Materialtype1 materialtype1, Materialtype2 materialtype2, Stock stock, Unit unit, String code, String name, BigDecimal price,
            int quantity, String description, Set<Coupondetail> coupondetails, Set<Orderdetail> orderdetails) {
        this.materialtype1 = materialtype1;
        this.materialtype2 = materialtype2;
        this.stock = stock;
        this.unit = unit;
        this.code = code;
        this.name = name;
        this.price = price;
        this.quantity = quantity;
        this.description = description;
        this.coupondetails = coupondetails;
        this.orderdetails = orderdetails;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idMaterialType1", nullable = false)
    public Materialtype1 getMaterialtype1() {
        return this.materialtype1;
    }

    public void setMaterialtype1(Materialtype1 materialtype1) {
        this.materialtype1 = materialtype1;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idMaterialType2", nullable = false)
    public Materialtype2 getMaterialtype2() {
        return this.materialtype2;
    }

    public void setMaterialtype2(Materialtype2 materialtype2) {
        this.materialtype2 = materialtype2;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idStock", nullable = false)
    public Stock getStock() {
        return this.stock;
    }

    public void setStock(Stock stock) {
        this.stock = stock;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idUnit")
    public Unit getUnit() {
        return this.unit;
    }

    public void setUnit(Unit unit) {
        this.unit = unit;
    }

    @Column(name = "code", nullable = false, length = 45)
    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    @Column(name = "name", nullable = false, length = 128)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "price", nullable = false, scale = 4)
    public BigDecimal getPrice() {
        return this.price;
    }

    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    @Column(name = "quantity", nullable = false)
    public int getQuantity() {
        return this.quantity;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    @Column(name = "description", length = 65535)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "material")
    public Set<Coupondetail> getCoupondetails() {
        return this.coupondetails;
    }

    public void setCoupondetails(Set<Coupondetail> coupondetails) {
        this.coupondetails = coupondetails;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "material")
    public Set<Orderdetail> getOrderdetails() {
        return this.orderdetails;
    }

    public void setOrderdetails(Set<Orderdetail> orderdetails) {
        this.orderdetails = orderdetails;
    }

    @Override
    public String toString() {
        return "Material [id=" + id + ", materialtype1=" + materialtype1
                + ", materialtype2=" + materialtype2 + ", stock=" + stock
                + ", unit=" + unit + ", code=" + code + ", name=" + name
                + ", price=" + price + ", quantity=" + quantity
                + ", description=" + description + ", coupondetails="
                + coupondetails + ", orderdetails=" + orderdetails + "]";
    }

    public static String getEntityname() {
        return "Material";
    }

    @Override
    public Object getValueByPropertyName(String propertyName) {
        // TODO Auto-generated method stub
        return null;
    }

    @Override
    public void verifyObject() {
        // TODO Auto-generated method stub
        
    }
}
