package com.luvsoft.entities;

// Generated May 12, 2016 9:26:32 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.luvsoft.utils.Utilities;

/**
 * Materialhistory generated by hbm2java
 */
@Entity
@Table(name = "materialhistory", catalog = "stockmanagement")
public class Materialhistory extends AbstractEntity implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private Integer id;
    private Material material;
    private int quantity;
    private BigDecimal averageInputPrice;
    private Date date;

    public Materialhistory() {
        quantity = 0;
        averageInputPrice = new BigDecimal(0.0d);
        date = Utilities.StringToDate("1/1/2000 01:00:00");
    }

    public Materialhistory(Material material, int quantity,
            BigDecimal averageInputPrice, Date date) {
        this.material = material;
        this.quantity = quantity;
        this.averageInputPrice = averageInputPrice;
        this.date = date;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idMaterial", nullable = false)
    public Material getMaterial() {
        return this.material;
    }

    public void setMaterial(Material material) {
        this.material = material;
    }

    @Column(name = "quantity", nullable = false)
    public int getQuantity() {
        return this.quantity;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    @Column(name = "averageInputPrice", nullable = false, scale = 4)
    public BigDecimal getAverageInputPrice() {
        return this.averageInputPrice;
    }

    public void setAverageInputPrice(BigDecimal averageInputPrice) {
        this.averageInputPrice = averageInputPrice;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "date", nullable = false, length = 19)
    public Date getDate() {
        return this.date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    @Override
    public Object getValueByPropertyName(String propertyName) {
        // TODO Auto-generated method stub
        return null;
    }

    @Override
    public void verifyObject() {
        
        
    }

    @Override
    public AbstractEntity cloneObject() {
        // TODO Auto-generated method stub
        return null;
    }
    
    public static String getEntityname() {
        return "Materialhistory";
    }

}
