package com.luvsoft.entities;

// Generated Apr 13, 2016 11:10:12 PM by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Materialinputhistory generated by hbm2java
 */
@Entity
@Table(name = "materialinputhistory", catalog = "stockmanagement")
public class Materialinputhistory extends AbstractEntity implements java.io.Serializable {
    /**
     * 
     */
    private static final long serialVersionUID = -7114152489337694967L;
    private Integer id;
    private Material material;
    private int quantity;
    private BigDecimal inputPrice;
    private Date date;

    public Materialinputhistory() {
    }

    public Materialinputhistory(Material material, int quantity,
            BigDecimal inputPrice, Date date) {
        this.material = material;
        this.quantity = quantity;
        this.inputPrice = inputPrice;
        this.date = date;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idMaterial", nullable = false)
    public Material getMaterial() {
        return this.material;
    }

    public void setMaterial(Material material) {
        this.material = material;
    }

    @Column(name = "quantity", nullable = false)
    public int getQuantity() {
        return this.quantity;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    @Column(name = "inputPrice", nullable = false, scale = 0)
    public BigDecimal getInputPrice() {
        return this.inputPrice;
    }

    public void setInputPrice(BigDecimal inputPrice) {
        this.inputPrice = inputPrice;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "date", nullable = false, length = 10)
    public Date getDate() {
        return this.date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public static String getEntityname() {
        return "Materialinputhistory";
    }
    
    @Override
    public Object getValueByPropertyName(String propertyName) {
        // TODO Auto-generated method stub
        return null;
    }

    @Override
    public void verifyObject() {
        this.quantity = (quantity < 0) ? 0 : quantity;
        this.inputPrice = (inputPrice == null) ? new BigDecimal(0.0f) : inputPrice;
    }

    @Override
    public AbstractEntity cloneObject() {
        // TODO Auto-generated method stub
        return null;
    }

}
