package com.luvsoft.entities;

// Generated Jan 26, 2016 10:06:12 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Receivingbill generated by hbm2java
 */
@Entity
@Table(name = "receivingbill", catalog = "stockmanagement")
public class Receivingbill extends AbstractEntity implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 996658298117657862L;
    private Integer id;
    private Coupon coupon;
    private Customer customer;
    private Order order;
    private String code;
    private String content;
    private Date date;
    private String note;
    private Set<Receivingbilldetail> receivingbilldetails = new HashSet<Receivingbilldetail>(0);

    public Receivingbill() {
    }

    public Receivingbill(Customer customer, String code, String content, Date date) {
        this.customer = customer;
        this.code = code;
        this.content = content;
        this.date = date;
    }

    public Receivingbill(Coupon coupon, Customer customer, Order order, String code, String content, Date date, String note,
            Set<Receivingbilldetail> receivingbilldetails) {
        this.coupon = coupon;
        this.customer = customer;
        this.order = order;
        this.code = code;
        this.content = content;
        this.date = date;
        this.note = note;
        this.receivingbilldetails = receivingbilldetails;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idCoupon")
    public Coupon getCoupon() {
        return this.coupon;
    }

    public void setCoupon(Coupon coupon) {
        this.coupon = coupon;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idCustomer", nullable = false)
    public Customer getCustomer() {
        return this.customer;
    }

    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idOrder")
    public Order getOrder() {
        return this.order;
    }

    public void setOrder(Order order) {
        this.order = order;
    }

    @Column(name = "code", nullable = false, length = 45)
    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    @Column(name = "content", nullable = false, length = 65535)
    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "date", nullable = false, length = 19)
    public Date getDate() {
        return this.date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    @Column(name = "note", length = 65535)
    public String getNote() {
        return this.note;
    }

    public void setNote(String note) {
        this.note = note;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "receivingbill")
    public Set<Receivingbilldetail> getReceivingbilldetails() {
        return this.receivingbilldetails;
    }

    public void setReceivingbilldetails(Set<Receivingbilldetail> receivingbilldetails) {
        this.receivingbilldetails = receivingbilldetails;
    }

    @Override
    public String toString() {
        return "Receivingbill [id=" + id + ", coupon=" + coupon + ", customer="
                + customer + ", order=" + order + ", code=" + code
                + ", content=" + content + ", date=" + date + ", note=" + note
                + ", receivingbilldetails=" + receivingbilldetails + "]";
    }

    public static String getEntityname() {
        return "Receivingbill";
    }
}
