package com.luvsoft.entities;

// Generated Jan 26, 2016 10:06:12 PM by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Spendingbill generated by hbm2java
 */
@Entity
@Table(name = "spendingbill", catalog = "stockmanagement")
public class Spendingbill extends AbstractEntity implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = -4565970400181930647L;
    private Integer id;
    private Integer idCoupon;
    private Customer customer;
    private String code;
    private String content;
    private Date date;
    private String note;
    private Set<Spendingbilldetail> spendingbilldetails = new HashSet<Spendingbilldetail>(0);

    public Spendingbill() {
    }

    public Spendingbill(String code, String content, Date date) {
        this.code = code;
        this.content = content;
        this.date = date;
    }

    public Spendingbill(Integer idCoupon, Customer customer, String code, String content, Date date, String note,
            Set<Spendingbilldetail> spendingbilldetails) {
        this.idCoupon = idCoupon;
        this.customer = customer;
        this.code = code;
        this.content = content;
        this.date = date;
        this.note = note;
        this.spendingbilldetails = spendingbilldetails;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "idCoupon")
    public Integer getIdCoupon() {
        return this.idCoupon;
    }

    public void setIdCoupon(Integer idCoupon) {
        this.idCoupon = idCoupon;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idCustomer")
    public Customer getCustomer() {
        return this.customer;
    }

    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

    @Column(name = "code", nullable = false, length = 45)
    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    @Column(name = "content", nullable = false, length = 65535)
    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "date", nullable = false, length = 19)
    public Date getDate() {
        return this.date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    @Column(name = "note", length = 65535)
    public String getNote() {
        return this.note;
    }

    public void setNote(String note) {
        this.note = note;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "spendingbill", cascade = CascadeType.ALL)
    public Set<Spendingbilldetail> getSpendingbilldetails() {
        return this.spendingbilldetails;
    }

    public void setSpendingbilldetails(Set<Spendingbilldetail> spendingbilldetails) {
        this.spendingbilldetails = spendingbilldetails;
    }

    @Override
    public String toString() {
        return "Spendingbill [id=" + id + ", coupon=" + idCoupon + ", customer="
                + customer + ", code=" + code + ", content=" + content
                + ", date=" + date + ", note=" + note
                + ", spendingbilldetails=" + spendingbilldetails + "]";
    }

    public static String getEntityname() {
        return "Spendingbill";
    }

    @Override
    public Object getValueByPropertyName(String propertyName) {
        // TODO Auto-generated method stub
        return null;
    }

    @Override
    public void verifyObject() {
        // TODO Auto-generated method stub
        
    }

    @Override
    public AbstractEntity cloneObject() {
        // TODO Auto-generated method stub
        return null;
    }
}
