package com.luvsoft.entities;

// Generated Jan 19, 2016 12:29:34 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Materialtype2 generated by hbm2java
 */
@Entity
@Table(name = "materialtype2", catalog = "stockmanagement")
public class Materialtype2 implements java.io.Serializable {

	private Integer id;
	private String name;
	private String description;
	private Set<Material> materials = new HashSet<Material>(0);

	public Materialtype2() {
	}

	public Materialtype2(String name) {
		this.name = name;
	}

	public Materialtype2(String name, String description,
			Set<Material> materials) {
		this.name = name;
		this.description = description;
		this.materials = materials;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 128)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "materialtype2")
	public Set<Material> getMaterials() {
		return this.materials;
	}

	public void setMaterials(Set<Material> materials) {
		this.materials = materials;
	}

}
