package com.luvsoft.entities;

// Generated Jan 19, 2016 12:29:34 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Unit generated by hbm2java
 */
@Entity
@Table(name = "unit", catalog = "stockmanagement")
public class Unit implements java.io.Serializable {

	private Integer id;
	private String name;
	private Set<Material> materials = new HashSet<Material>(0);

	public Unit() {
	}

	public Unit(String name) {
		this.name = name;
	}

	public Unit(String name, Set<Material> materials) {
		this.name = name;
		this.materials = materials;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 128)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "unit")
	public Set<Material> getMaterials() {
		return this.materials;
	}

	public void setMaterials(Set<Material> materials) {
		this.materials = materials;
	}

}
